# Generated by Django 4.2.4 on 2023-09-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablecrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='det',
        ),
    ]
